config/routes.rb
Rails.application.routes.draw do
  get 'reports/cpu'
  get 'reports/disk'
  get 'reports/process', to: 'reports#process_report'

  devise_for :users

  resources :servers, only: [:index, :show, :edit, :update] do
    resources :cpu_data, only: :index
    resources :disk_data, only: :index
    resources :process_data, only: [:index, :show]
  end

  root 'home#welcome'

end

app/models/server.rb
# This class holds the server objects
# validates hostname and user presence
class Server < ActiveRecord::Base
  validates :hostname, presence: true
  validates :user, presence: true

  belongs_to :user, inverse_of: :servers

  has_many :cpu_data, class_name: :ServerCpuDatum, inverse_of: :server
  has_many :disk_data, class_name: :ServerDiskDatum, inverse_of: :server
  has_many :process_data, class_name: :ServerProcessDatum, inverse_of: :server

  attr_accessor :clear_data

  before_save :clear_server_data

  def to_json(*a)
    { 'hostname' => hostname }.to_json(*a)
  end

  # Clears the all server data if user checked the option
  # on server edit form
  def clear_server_data
    if @clear_data == '1'
      cpu_data.each(&:destroy)
      disk_data.each(&:destroy)
      process_data.each(&:destroy)
    end
  end

  # Returns the latest cpu usage data retrieved from server
  def current_cpu_usage
    cpu_data.latest_usage || 0
  end

  # Returns the latest disk usage data retrieved from server
  def current_disk_usage
    disk_data.latest_usage || 0
  end

  # Returns the latest process count data retrieved from server
  def current_process_count
    process_data.latest_process_count || 0
  end

  # Returns the last 10 cpu data cpu usage in reverse order
  # return 10,12,15,13
  def mini_cpu_graph_data
    cpu_data.descending.limit(10).pluck(:cpu_usage).reverse.join(',')
  end

  # Returns the last 30 cpu data cpu usage
  def cpu_graph_data
    cpu_data.descending.limit(30).pluck(:cpu_usage).reverse
  end

  # Returns the last 10 disk data disk usage in reverse order
  # return 10,12,15,13
  def mini_disk_graph_data
    disk_data.descending.limit(10).pluck(:disk_usage).reverse.join(',')
  end

  # Returns the last 30 disk data disk usage
  def disk_graph_data
    disk_data.descending.limit(30).pluck(:disk_usage).reverse
  end

  # Returns the last 10 process data process count in reverse order
  # return 10,12,15,13
  def mini_process_count_data
    process_data.descending.limit(10).pluck(:process_count).reverse.join(',')
  end

  # Returns the last 30 process data process count in reverse order
  def process_count_data
    process_data.descending.limit(30).pluck(:process_count).reverse
  end

  # Returns the average cpu usage
  # If no cpu usage data exists returns 0
  def average_cpu_usage
    cpu_data.average(:cpu_usage).to_i || 0
  end

  # Returns the average disk usage
  # If no disk usage data exists returns 0
  def average_disk_usage
    disk_data.average(:disk_usage).to_i || 0
  end

  # Returns the average process count
  # If no process count data exists returns 0
  def average_process_count
    process_data.average(:process_count).to_i || 0
  end

  # Returns the user created custom name.
  # If no custom name returns the servers hostname
  def name
    custom_name || hostname
  end
end

app/controllers/servers_controller.rb
class ServersController < ApplicationController
  before_action :set_server, only: [:show, :edit, :update]

  # GET /servers
  # GET /servers.json
  def index
    @servers = current_user.servers.all
  end

  # GET /servers/1
  # GET /servers/1.json
  def show
  end

  # GET /servers/1/edit
  def edit
  end

  # PATCH/PUT /servers/1
  # PATCH/PUT /servers/1.json
  def update
    respond_to do |format|
      if @server.update(server_params)
        format.html { redirect_to server_path(@server), notice: 'Server was successfully updated.' }
        format.json { render :show, status: :ok, location: @server }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_server
    @server = current_user.servers.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def server_params
    params.require(:server).permit(:custom_name, :clear_data, :cpu_alert, :disk_alert, :process_alert)
  end
end

app/views/servers/_form.html.erb
<%= form_for(server) do |f| %>
    <% if server.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(server.errors.count, "error") %> prohibited this server from being saved:</h2>

          <ul>
            <% server.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :hostname %><br>
      <%= server.hostname %>
    </div>

    <div class="form-group">
      <%= f.label :custom_name %><br>
      <%= f.text_field :custom_name, class: 'form-control' %>
    </div>

    <div class="checkbox">
      <label>
        <%= f.check_box :clear_data %> Clear Server Data
      </label>
    </div>

    <div class="checkbox">
      <label>
        <%= f.check_box :cpu_alert %> Alert On High Cpu Usage
      </label>
    </div>

    <div class="checkbox">
      <label>
        <%= f.check_box :disk_alert %> Alert On High Disk Usage
      </label>
    </div>

    <div class="checkbox">
      <label>
        <%= f.check_box :process_alert %> Alert On High Process Count
      </label>
    </div>

    <%= f.submit class: 'btn btn-default' %>
<% end %>

app/views/servers/edit.html.erb
<h1>Editing Server</h1>

<%= render 'form', locals: { server: @server } %>

<hr />

<%= link_to 'Show', @server %> |
<%= link_to 'Back', servers_path %>

app/views/servers/index.html.erb
<h1>My Servers</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Cpu Usage</th>
      <th>Disk Usage</th>
      <th>Process Count</th>
      <th>Last Data Received At</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @servers.each do |server| %>
      <tr>
        <td><%= link_to server.name, server_path(server) %></td>
        <td class="cpu_data"><%= server.mini_cpu_graph_data %></td>
        <td class="disk_data"><%= server.mini_disk_graph_data %></td>
        <td class="process_data"><%= server.mini_process_count_data %></td>
        <td><%= l server.last_data_sent_at, format: :short if server.last_data_sent_at %></td>
        <td><%= link_to 'Edit', edit_server_path(server) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/servers/show.html.erb
<h3><%= @server.name %></h3>

<p>
  <strong>Hostname:</strong>
  <%= @server.hostname %>
</p>

<p>
  <strong>Custom Name:</strong>
  <%= @server.custom_name %>
</p>

<p>
  <strong>Added At:</strong>
  <%= l @server.created_at, format: :short %>
</p>

<p>
  <strong>Last Data Received At:</strong>
  <%= l @server.last_data_sent_at, format: :short if @server.last_data_sent_at %>
</p>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading"><strong>Current Data</strong></div>
      <div class="panel-body">
        <div class="col-lg-4">
          <div id="cpu_gauge" data-current-value="<%= @server.current_cpu_usage %>"></div>
        </div>

        <div class="col-lg-4">
          <div id="disk_gauge" data-current-value="<%= @server.current_disk_usage %>"></div>
        </div>

        <div class="col-lg-4">
          <div id="process_gauge" data-current-value="<%= @server.current_process_count %>"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading"><strong>Average Data</strong></div>
      <div class="panel-body">
        <div class="col-lg-4">
          <div id="average_cpu_gauge" data-current-value="<%= @server.average_cpu_usage %>"></div>
        </div>

        <div class="col-lg-4">
          <div id="average_disk_gauge" data-current-value="<%= @server.average_disk_usage %>"></div>
        </div>

        <div class="col-lg-4">
          <div id="average_process_gauge" data-current-value="<%= @server.average_process_count %>"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= link_to 'Edit Server', edit_server_path(@server) %> |
<%= link_to 'Display All CPU Data', server_cpu_data_path(@server) %> |
<%= link_to 'Display All Disk Data', server_disk_data_path(@server) %> |
<%= link_to 'Display All Process Data', server_process_data_path(@server) %>