config/routes.rb
Rails.application.routes.draw do
  get 'reports/cpu'
  get 'reports/disk'
  get 'reports/process', to: 'reports#process_report'

  devise_for :users

  resources :servers, only: [:index, :show, :edit, :update] do
    resources :cpu_data, only: :index
    resources :disk_data, only: :index
    resources :process_data, only: [:index, :show]
  end

  root 'home#welcome'

end

app/views/shared/_data_nav_links.html.erb
<%= link_to 'Return To Server Page', server_path(server) %> |
<%= link_to 'Display All CPU Data', server_cpu_data_path(server) %> |
<%= link_to 'Display All Disk Data', server_disk_data_path(server) %> |
<%= link_to 'Display All Process Data', server_process_data_path(server) %>

app/views/shared/_flash_messages.html.erb
<% if notice.present? %>
    <div class="alert alert-success" role="alert">
      <%= notice %>
    </div>
<% end %>

<% if alert.present? %>
    <div class="alert alert-danger" role="alert">
      <%= alert %>
    </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
  <p>&copy; 2016 Fatih Aytaç</p>
</footer>

app/views/shared/_header.html.erb
<div class="header clearfix">
  <nav>
    <ul class="nav nav-pills pull-right">
      <% if current_user %>
          <li role="presentation">
            <%= link_to 'Servers', servers_path %>
          </li>
          <li role="presentation">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              Reports <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to 'CPU Reports', reports_cpu_path %>
              </li>
              <li>
                <%= link_to 'Disk Reports', reports_disk_path %>
              </li>
              <li>
                <%= link_to 'Process Reports', reports_process_path %>
              </li>
            </ul>
          </li>
          <li role="presentation">
            <%= link_to 'Edit Account', edit_user_registration_path %>
          </li>
          <li role="presentation">
            <%= link_to 'Logout', destroy_user_session_path %>
          </li>
      <% else %>
          <li role="presentation">
            <%= link_to 'Home', root_path %>
          </li>
          <li role="presentation">
            <%= link_to 'Sign In', new_user_session_path %>
          </li>
      <% end %>
      </li>
    </ul>
  </nav>
  <h3 class="text-muted">
    <%= link_to 'Crossover Project', root_path %>
  </h3>
</div>

app/views/shared/_pdf_footer.html.erb
<footer class="footer">
  <p>&copy; 2016 Fatih Aytaç</p>
</footer>

</div>
</body>
</html>

app/views/shared/_pdf_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Report</title>

  <%= wicked_pdf_stylesheet_link_tag 'application' %>
  <%= wicked_pdf_javascript_include_tag 'application' %>
</head>

<body>
<div class="container">

<div class="header clearfix">
  <h3 class="text-muted">
    <%= link_to 'Crossover Project', root_path %>
  </h3>
</div>